repos:
  - repo: builtin
    hooks:
      - id: no-commit-to-branch
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry : clang-format -i
        language: system
        files: ^LINC/.*\.(c|h)$